export const productTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_CATEGORY_PRODUCT: 'SET_CATEGORY_PRODUCT',
    SET_PUBLISHSER: 'SET_PUBLISHSER',
    SET_BRAND: 'SET_BRAND',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',
    RESET_CATEGORY: 'RESET_CATEGORY',
    ADD_BRAND_SUCCESS: 'ADD_BRAND_SUCCESS',
    ADD_BRAND_FAIL: 'ADD_BRAND_FAIL',
    UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAIL: 'UPDATE_BRAND_FAIL',
    RESET_BRAND: 'RESET_BRAND',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL',
    RESET_PRODUCT: 'RESET_PRODUCT',
    BRAND_SET_PAGE: 'BRAND_SET_PAGE',
    BRAND_SET_TOTAL_PAGE: 'BRAND_SET_TOTAL_PAGE',
    CATEGORY_SET_PAGE: 'CATEGORY_SET_PAGE',
    CATEGORY_SET_TOTAL_PAGE: 'CATEGORY_SET_TOTAL_PAGE',
    ORDER_SET_PAGE: 'ORDER_SET_PAGE',
    ORDER_SET_TOTAL_PAGE: 'ORDER_SET_TOTAL_PAGE',
    ORDER_SET_DATA: "ORDER_SET_DATA"

}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT'
}